eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
#  profiles:
#    active: test
  application:
    name: api-gate-way-scg
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: first-service
              uri: lb://FIRST-SERVICE/
              predicates:
                - Path=/fs/**
            - id: second-service
              uri: lb://second-service/
              predicates:
               - Path=/ss/**
server:
  port: 9000



